// backend/config/allergenMap.js

export const allergenMap = {
  // 1. DAIRY (Upgraded with Pakistani terms)
  milk: [
    "milk",
    "casein",
    "caseinate",
    "whey",
    "lactalbumin",
    "lactoglobulin",
    "lactulose",
    "nougat",
    "cream",
    "butter",
    "cheese",
    "ghee",
    "yogurt",
    "curd",
    "buttermilk",
    "paneer",
    "custard",
    "half-and-half",
    "dairy",
    "khoya",
    "mawa",
    "malai",
    "lassi",
    "rabri",
  ],

  // 2. EGGS
  eggs: [
    "egg",
    "eggs",
    "albumin",
    "albumen",
    "lysozyme",
    "mayonnaise",
    "meringue",
    "ovalbumin",
    "surimi",
    "globulin",
    "vitellin",
  ],

  // 3. WHEAT / GLUTEN (Upgraded with local flour names)
  wheat: [
    "wheat",
    "gluten",
    "bran",
    "bulgur",
    "couscous",
    "farina",
    "seitan",
    "semolina",
    "spelt",
    "flour",
    "durum",
    "einkorn",
    "emmer",
    "kamut",
    "maida",
    "sooji",
    "suji",
    "atta",
    "daliya",
  ],

  // 4. SOY
  soy: [
    "soy",
    "soya",
    "soybean",
    "soybeans",
    "edamame",
    "miso",
    "natto",
    "shoyu",
    "tofu",
    "tamari",
    "tempeh",
    "textured vegetable protein",
    "tvp",
  ],

  // 5. PEANUTS (Added local name)
  peanuts: [
    "peanut",
    "peanuts",
    "arachis",
    "goober",
    "mandelonas",
    "groundnuts",
    "valencias",
    "arachis oil",
    "moongphali",
  ],

  // 6. TREE NUTS (Added local names)
  treenuts: [
    "almond",
    "almonds",
    "badam",
    "walnut",
    "walnuts",
    "akhrot",
    "pecan",
    "pecans",
    "cashew",
    "cashews",
    "kaju",
    "pistachio",
    "pistachios",
    "pista",
    "hazelnut",
    "hazelnuts",
    "macadamia",
    "pine nut",
    "chilgoza",
    "brazil nut",
    "marzipan",
    "praline",
  ],

  // 7. FISH
  fish: [
    "fish",
    "anchovies",
    "bass",
    "catfish",
    "cod",
    "flounder",
    "grouper",
    "haddock",
    "hake",
    "halibut",
    "herring",
    "mahi mahi",
    "perch",
    "pike",
    "pollock",
    "salmon",
    "snapper",
    "swordfish",
    "tilapia",
    "trout",
    "tuna",
    "machli",
  ],

  // 8. CRUSTACEANS & MOLLUSCS (Shellfish)
  shellfish: [
    "shellfish",
    "crustacean",
    "mollusc",
    "shrimp",
    "prawn",
    "jhinga",
    "crab",
    "lobster",
    "crawfish",
    "krill",
    "oyster",
    "scallop",
    "squid",
    "calamari",
    "octopus",
    "clam",
    "mussel",
  ],

  // 9. SESAME (Highly common in bakery items)
  sesame: ["sesame", "tahini", "til", "benne", "gomasio", "halva"],

  // 10. MUSTARD
  mustard: ["mustard", "sarson", "rai", "mustard seed", "mustard powder"],

  // 11. CELERY
  celery: ["celery", "celeriac", "celery salt", "celery seed"],

  // 12. SULFITES (Chemical preservatives in dried fruits and drinks)
  sulfites: [
    "sulfite",
    "sulphite",
    "sulfur dioxide",
    "potassium bisulfite",
    "sodium sulfite",
    "metabisulfite",
    "e220",
    "e221",
    "e222",
    "e223",
    "e224",
    "e225",
    "e226",
    "e227",
    "e228",
  ],

  // 13. LUPIN (A legume increasingly used as a flour alternative)
  lupin: ["lupin", "lupine", "lupin flour", "lupin seed"],
};
